"""Shared constants for collection names and roles."""

DOCS_COLLECTION = "jurislab_documents"
SIM_COLLECTION = "jurislab_scenario_docs"

DISCLAIMER_CASE_STUDY = (
    "> **Disclaimer:** This case study was generated by JurisLab's multi-agent simulation and is "
    "for educational and informational purposes only. It is not legal advice, does not reflect a "
    "real case, and does not create an attorney-client relationship. Consult a qualified legal "
    "professional regarding any real dispute."
)

DISCLAIMER_REVIEW = (
    "> **Disclaimer:** This review report was generated by JurisLab and is informational and "
    "educational only. It is not legal advice and does not create an attorney-client relationship."
)

EDUCATIONAL_NOT_ADVICE = "Educational and informational. Not legal advice."
