"""Review report assembly from extraction findings (PRD §5.2, §6.5)."""

from __future__ import annotations

from app.exports.markdown import with_disclaimer
from app.review.extractor import ClauseExtraction
from app.review.risk import RiskSummary, risk_guidelines, risk_insight

DISCLAIMER_LINE = (
    "\n\n---\n\n*This Review Report was generated by JurisFlow. It is informational and "
    "educational only, and is not legal advice or a substitute for professional review by a "
    "qualified lawyer.*"
)


def build_review_markdown(
    *,
    document_title: str,
    executive_summary: str,
    findings: list[ClauseExtraction],
    risk: RiskSummary,
    suggested_questions: list[str],
    obligations: list[str] | None = None,
    analysis_warning: str = "",
    abstentions: list[str] | None = None,
) -> str:
    sections: list[str] = [f"# Review Report — {document_title}", ""]

    sections.append("## Executive Summary")
    sections.append(executive_summary or "A review of the document was completed.")
    sections.append("")

    sections.append("## Risk Overview")
    sections.append(
        f"- Confirmed high-risk clauses (KM-backed): **{risk.high_count}**\n"
        f"- Confirmed medium-risk clauses (KM-backed): **{risk.medium_count}**\n"
        f"- Low / informational clauses: **{risk.low_count}**\n"
        f"- Obligation load (confirmed): **{risk.obligation_count}** duties\n"
        f"- Balance score: **{risk.balance_score:+.2f}** (toward first party when positive "
        f"obligations are concentrated on that side)"
    )
    manual = [
        f for f in findings if getattr(f, "support_status", "") == "manual_review"
    ]
    if manual:
        sections.append(
            f"- **Manual-review advisories (no KM support):** **{len(manual)}** — "
            "suggested by the model but not counted as confirmed risk"
        )
    sections.append("")

    guidelines = risk_guidelines()
    sections.append("## Risk Flagging Guidelines")
    for level in guidelines["levels"]:
        sections.append(
            f"- {level['flag']} **{level['label']}** — {level['summary']}\n"
            f"  - Default clause types: {', '.join(level['clause_types'])}\n"
            f"  - Recommended action: {level['recommended_action']}"
        )
    sections.append("")
    for rule in guidelines["assignment_rules"]:
        sections.append(f"- **{rule['rule']}**: {rule['detail']}")
    sections.append("")

    clauses = [f for f in findings if f.clause_type != "general"]
    sections.append("## Key Clauses and Risks")
    if not clauses:
        sections.append("No clauses were identified.")
    else:
        for i, f in enumerate(clauses, start=1):
            marker = {"high": "🔴", "medium": "🟡", "low": "🟢"}.get(f.risk_level, "🟢")
            insight = risk_insight(
                clause_type=f.clause_type,
                risk_level=f.risk_level,
                obligation=f.obligation,
                grounded=f.grounded,
                support_status=getattr(f, "support_status", "") or "",
                suggested_risk_level=getattr(f, "suggested_risk_level", "") or "",
            )
            support = getattr(f, "support_status", "") or ""
            support_note = ""
            if support == "manual_review":
                suggested = getattr(f, "suggested_risk_level", "") or "medium"
                support_note = (
                    f" *(manual review — model suggested {suggested.upper()}, "
                    "no KM artefact support)*"
                )
            elif support == "km_confirmed":
                support_note = " *(KM-confirmed)*"
            elif not f.grounded:
                support_note = " *(not grounded — abstained)*"
            sections.append(
                f"{i}. **{f.clause_type.title()}** — {marker} risk: {f.risk_level.upper()}{support_note}\n"
                f"   - *Excerpt:* “{f.text}”"
            )
            if f.explanation:
                sections.append(f"   - Why it matters: {f.explanation}")
            if f.plain_language:
                sections.append(f"   - In simple terms: {f.plain_language}")
            sections.append(f"   - Why this risk level: {insight['risk_rationale']}")
            sections.append(
                f"   - **Recommended action:** {insight['recommended_action']}"
            )
            if getattr(f, "proposed_change", None):
                sections.append(
                    f"   - **Proposed Contract Amendment:** {f.proposed_change}"
                )
            if getattr(f, "change_rationale", None):
                sections.append(f"   - **Amendment Rationale:** {f.change_rationale}")
            if f.obligation:
                sections.append(
                    "   - **Obligation:** this clause imposes a duty on a party."
                )
    sections.append("")

    sections.append("## Proposed Contract Modifications & Remediation")
    remediations = [f for f in clauses if getattr(f, "proposed_change", None)]
    if not remediations:
        sections.append(
            "No specific clause amendments were proposed for this document."
        )
    else:
        for i, f in enumerate(remediations, start=1):
            sections.append(
                f"### {i}. {f.clause_type.title()} Amendment ({f.risk_level.upper()} Risk)\n"
                f"- **Current Excerpt:** “{f.text}”\n"
                f"- **Proposed Language:**\n"
                f"  > {f.proposed_change}\n"
                f"- **Contextual Rationale:** {f.change_rationale or 'Remediates identified contractual imbalance and establishes market-standard protections.'}\n"
            )
    sections.append("")

    manual_advisories = [
        f for f in clauses if getattr(f, "support_status", "") == "manual_review"
    ]
    if manual_advisories:
        sections.append("## Manual Review Advisories (No KM Support)")
        sections.append(
            "These clauses were suggested by the model but could not be substantiated "
            "against Knowledge Hub artefacts. They are **not** counted as confirmed risks."
        )
        for i, f in enumerate(manual_advisories, start=1):
            suggested = getattr(f, "suggested_risk_level", "") or "medium"
            sections.append(
                f"{i}. **{f.clause_type.title()}** — model suggested {suggested.upper()}\n"
                f"   - *Excerpt:* “{f.text}”\n"
                f"   - **Action:** Advise counsel to review manually."
            )
        sections.append("")

    if abstentions:
        sections.append("## Items Not Analyzed")
        sections.append("\n".join(f"- {a}" for a in abstentions))
        sections.append("")

    sections.append("## Obligations Checklist")
    obls = obligations or [
        f"- {f.clause_type}: {f.text[:140]}" for f in clauses if f.obligation
    ]
    sections.append("\n".join(obls) if obls else "- No obligations identified.")
    sections.append("")

    sections.append("## Suggested Questions for a Lawyer")
    questions = suggested_questions or [
        "- What are my actual obligations and their deadlines under the identified clauses?",
        "- Which clauses favor the other party, and are they enforceable in my jurisdiction?",
        "- What are the financial consequences of termination, penalties, or indemnities?",
        "- Should I negotiate this dispute-resolution or confidentiality clause before signing?",
    ]
    sections.append("\n".join(questions))

    if analysis_warning:
        sections.append("\n\n## Review Notes")
        sections.append(analysis_warning)

    return with_disclaimer("\n".join(sections), kind="Review Report")
