"""Review report assembly from extraction findings (PRD §5.2, §6.5)."""

from __future__ import annotations

from app.exports.markdown import with_disclaimer
from app.review.extractor import ClauseExtraction
from app.review.risk import RiskSummary, risk_insight

DISCLAIMER_LINE = (
    "\n\n---\n\n*This Review Report was generated by JurisLab. It is informational and "
    "educational only, and is not legal advice or a substitute for professional review by a "
    "qualified lawyer.*"
)


def build_review_markdown(
    *,
    document_title: str,
    executive_summary: str,
    findings: list[ClauseExtraction],
    risk: RiskSummary,
    suggested_questions: list[str],
    obligations: list[str] | None = None,
    analysis_warning: str = "",
    abstentions: list[str] | None = None,
) -> str:
    sections: list[str] = [f"# Review Report — {document_title}", ""]

    sections.append("## Executive Summary")
    sections.append(executive_summary or "A review of the document was completed.")
    sections.append("")

    sections.append("## Risk Overview")
    sections.append(
        f"- High-risk clauses: **{risk.high_count}**\n"
        f"- Medium-risk clauses: **{risk.medium_count}**\n"
        f"- Low-risk clauses: **{risk.low_count}**\n"
        f"- Obligation load: **{risk.obligation_count}** duties\n"
        f"- Balance score: **{risk.balance_score:+.2f}** (toward first party when positive "
        f"obligations are concentrated on that side)"
    )
    sections.append("")

    clauses = [f for f in findings if f.clause_type != "general"]
    sections.append("## Key Clauses and Risks")
    if not clauses:
        sections.append("No clauses were identified.")
    else:
        for i, f in enumerate(clauses, start=1):
            marker = {"high": "🔴", "medium": "🟡", "low": "🟢"}.get(f.risk_level, "🟢")
            grounded = "" if f.grounded else " *(not grounded — abstained)*"
            insight = risk_insight(
                clause_type=f.clause_type,
                risk_level=f.risk_level,
                obligation=f.obligation,
                grounded=f.grounded,
            )
            sections.append(
                f"{i}. **{f.clause_type.title()}** — {marker} risk: {f.risk_level.upper()}{grounded}\n"
                f"   - *Excerpt:* “{f.text}”"
            )
            if f.explanation:
                sections.append(f"   - Why it matters: {f.explanation}")
            if f.plain_language:
                sections.append(f"   - In simple terms: {f.plain_language}")
            sections.append(f"   - Why this risk level: {insight['risk_rationale']}")
            sections.append(
                f"   - **Recommended action:** {insight['recommended_action']}"
            )
            if getattr(f, "proposed_change", None):
                sections.append(
                    f"   - **Proposed Contract Amendment:** {f.proposed_change}"
                )
            if getattr(f, "change_rationale", None):
                sections.append(f"   - **Amendment Rationale:** {f.change_rationale}")
            if f.obligation:
                sections.append(
                    "   - **Obligation:** this clause imposes a duty on a party."
                )
    sections.append("")

    sections.append("## Proposed Contract Modifications & Remediation")
    remediations = [f for f in clauses if getattr(f, "proposed_change", None)]
    if not remediations:
        sections.append(
            "No specific clause amendments were proposed for this document."
        )
    else:
        for i, f in enumerate(remediations, start=1):
            sections.append(
                f"### {i}. {f.clause_type.title()} Amendment ({f.risk_level.upper()} Risk)\n"
                f"- **Current Excerpt:** “{f.text}”\n"
                f"- **Proposed Language:**\n"
                f"  > {f.proposed_change}\n"
                f"- **Contextual Rationale:** {f.change_rationale or 'Remediates identified contractual imbalance and establishes market-standard protections.'}\n"
            )
    sections.append("")

    if abstentions:
        sections.append("## Items Not Analyzed")
        sections.append("\n".join(f"- {a}" for a in abstentions))
        sections.append("")

    sections.append("## Obligations Checklist")
    obls = obligations or [
        f"- {f.clause_type}: {f.text[:140]}" for f in clauses if f.obligation
    ]
    sections.append("\n".join(obls) if obls else "- No obligations identified.")
    sections.append("")

    sections.append("## Suggested Questions for a Lawyer")
    questions = suggested_questions or [
        "- What are my actual obligations and their deadlines under the identified clauses?",
        "- Which clauses favor the other party, and are they enforceable in my jurisdiction?",
        "- What are the financial consequences of termination, penalties, or indemnities?",
        "- Should I negotiate this dispute-resolution or confidentiality clause before signing?",
    ]
    sections.append("\n".join(questions))

    if analysis_warning:
        sections.append("\n\n## Review Notes")
        sections.append(analysis_warning)

    return with_disclaimer("\n".join(sections), kind="Review Report")
