"""Markdown rendering and PDF export (PRD §5.1, §5.2, §6.6)."""

from __future__ import annotations

from io import BytesIO

from reportlab.lib import colors  # type: ignore[import-untyped]
from reportlab.lib.pagesizes import A4  # type: ignore[import-untyped]
from reportlab.lib.styles import (  # type: ignore[import-untyped]
    ParagraphStyle,
    getSampleStyleSheet,
)
from reportlab.lib.units import mm  # type: ignore[import-untyped]
from reportlab.platypus import (  # type: ignore[import-untyped]
    Paragraph,
    SimpleDocTemplate,
    Spacer,
)

DISCLAIMER = (
    "> **Disclaimer:** This {kind} was generated by JurisFlow and is for educational and "
    "informational purposes only. It is not legal advice and does not create an "
    "attorney-client relationship. Laws vary by jurisdiction; consult a qualified legal "
    "professional for advice about your specific situation."
)


def with_disclaimer(markdown: str, kind: str = "document") -> str:
    return f"{markdown.strip()}\n\n{DISCLAIMER.format(kind=kind)}\n"


def render_report_markdown(
    *,
    title: str,
    sections: list[tuple[str, str]],
    kind: str = "document",
) -> str:
    parts = [f"# {title}\n"]
    for heading, body in sections:
        parts.append(f"## {heading}\n")
        parts.append(body)
    return with_disclaimer("\n\n".join(parts), kind=kind)


def markdown_to_pdf(markdown: str) -> bytes:
    """Render a subset of Markdown (headings, bullets, bold, blockquote) to PDF bytes."""
    styles = getSampleStyleSheet()
    h1 = ParagraphStyle("H1", parent=styles["Title"], fontSize=18, spaceAfter=12)
    h2 = ParagraphStyle(
        "H2", parent=styles["Heading2"], fontSize=13, spaceAfter=8, spaceBefore=14
    )
    body = ParagraphStyle("Body", parent=styles["BodyText"], fontSize=9.5, leading=13)
    code = ParagraphStyle(
        "Code",
        parent=body,
        fontName="Courier",
        backColor=colors.Color(0.95, 0.95, 0.95),
    )

    buf = BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=18 * mm, rightMargin=18 * mm)
    story: list = []
    for raw_line in markdown.splitlines():
        line = raw_line.rstrip()
        if not line.strip():
            story.append(Spacer(1, 4))
            continue
        if line.startswith("```"):
            continue
        if line.startswith("> "):
            story.append(Paragraph(_escape(line[2:]), body))
            continue
        if line.startswith("#### "):
            story.append(Paragraph(f"<b>{_escape(line[5:])}</b>", body))
        elif line.startswith("### "):
            story.append(Paragraph(f"<b>{_escape(line[4:])}</b>", body))
        elif line.startswith("## "):
            story.append(Paragraph(_escape(line[3:]), h2))
        elif line.startswith("# "):
            story.append(Paragraph(_escape(line[2:]), h1))
        elif line.startswith("- "):
            story.append(Paragraph(f"• {_escape(line[2:])}", body))
        else:
            story.append(
                Paragraph(_escape(line), code if line.startswith("    ") else body)
            )
    doc.build(story)
    return buf.getvalue()


def _escape(text: str) -> str:
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
